// Code generated by ogen, DO NOT EDIT.

package genapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ApplyEditOperation          OperationName = "ApplyEdit"
	CommitDocumentOperation     OperationName = "CommitDocument"
	CreateSessionOperation      OperationName = "CreateSession"
	GetBlocksOperation          OperationName = "GetBlocks"
	GetCandidatesOperation      OperationName = "GetCandidates"
	GetDiffOperation            OperationName = "GetDiff"
	GetHealthOperation          OperationName = "GetHealth"
	GetHistoryOperation         OperationName = "GetHistory"
	GetModelStatusOperation     OperationName = "GetModelStatus"
	GetSessionMessagesOperation OperationName = "GetSessionMessages"
	ListModelsOperation         OperationName = "ListModels"
	ListModesOperation          OperationName = "ListModes"
	ListSessionsOperation       OperationName = "ListSessions"
	ListToolsOperation          OperationName = "ListTools"
	OpenDocumentOperation       OperationName = "OpenDocument"
	ProvisionModelOperation     OperationName = "ProvisionModel"
	StartModelOperation         OperationName = "StartModel"
	StartTurnOperation          OperationName = "StartTurn"
	StopModelOperation          OperationName = "StopModel"
)
