// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"context"
	"net/http"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ApplyEdit implements applyEdit operation.
	//
	// POST /documents/{id}/edits
	ApplyEdit(ctx context.Context, req *BlockEdit, params ApplyEditParams) (*Revision, error)
	// CommitDocument implements commitDocument operation.
	//
	// POST /documents/{id}/commits
	CommitDocument(ctx context.Context, params CommitDocumentParams) (*Revision, error)
	// CreateSession implements createSession operation.
	//
	// POST /sessions
	CreateSession(ctx context.Context, req *CreateSessionRequest) (*Session, error)
	// GetBlocks implements getBlocks operation.
	//
	// GET /documents/{id}/blocks
	GetBlocks(ctx context.Context, params GetBlocksParams) ([]Block, error)
	// GetCandidates implements getCandidates operation.
	//
	// GET /documents/{id}/blocks/{bid}/candidates
	GetCandidates(ctx context.Context, params GetCandidatesParams) ([]Candidate, error)
	// GetDiff implements getDiff operation.
	//
	// GET /documents/{id}/diff
	GetDiff(ctx context.Context, params GetDiffParams) ([]WordEdit, error)
	// GetHealth implements getHealth operation.
	//
	// Liveness check.
	//
	// GET /health
	GetHealth(ctx context.Context) (*Health, error)
	// GetHistory implements getHistory operation.
	//
	// GET /documents/{id}/history
	GetHistory(ctx context.Context, params GetHistoryParams) ([]Revision, error)
	// GetModelStatus implements getModelStatus operation.
	//
	// GET /models/{name}/status
	GetModelStatus(ctx context.Context, params GetModelStatusParams) (*LiveStateResponse, error)
	// GetSessionMessages implements getSessionMessages operation.
	//
	// GET /sessions/{id}/messages
	GetSessionMessages(ctx context.Context, params GetSessionMessagesParams) ([]Message, error)
	// ListDirectory implements listDirectory operation.
	//
	// List one directory's direct, non-recursive entries (ADR-0035).
	//
	// GET /directories
	ListDirectory(ctx context.Context, params ListDirectoryParams) (*DirectoryListing, error)
	// ListModels implements listModels operation.
	//
	// Discover the servable fleet (ADR-0018).
	//
	// GET /models
	ListModels(ctx context.Context) ([]Model, error)
	// ListModes implements listModes operation.
	//
	// GET /modes
	ListModes(ctx context.Context) ([]Mode, error)
	// ListSessions implements listSessions operation.
	//
	// GET /sessions
	ListSessions(ctx context.Context, params ListSessionsParams) ([]Session, error)
	// ListTools implements listTools operation.
	//
	// GET /tools
	ListTools(ctx context.Context) ([]ToolDef, error)
	// OpenDocument implements openDocument operation.
	//
	// Open/create a document by path; returns its surrogate id.
	//
	// POST /documents
	OpenDocument(ctx context.Context, req *OpenDocumentRequest) (*Document, error)
	// ProvisionModel implements provisionModel operation.
	//
	// POST /models/{name}/provision
	ProvisionModel(ctx context.Context, params ProvisionModelParams) (*ProvisionResponse, error)
	// SaveDocument implements saveDocument operation.
	//
	// The manual-edit wire path (ADR-0038): the client's whole block-tree snapshot. Array order =
	// position; a block with no `id` is new (the engine mints a UUID, ADR-0020 §3); an `id` present in
	// the current tree but absent from the request is deleted; a changed `kind`/`parentId` is
	// retyped/moved. The engine reconciles, normalizes on write and formats on commit, and commits
	// `autosave @ <ts>` iff anything changed (a no-op returns the current HEAD). A manual save of a block
	// drops its open candidates.
	//
	// PUT /documents/{id}/tree
	SaveDocument(ctx context.Context, req *SaveTreeRequest, params SaveDocumentParams) (*Revision, error)
	// StartModel implements startModel operation.
	//
	// POST /models/{name}/start
	StartModel(ctx context.Context, params StartModelParams) (*LiveStateResponse, error)
	// StopModel implements stopModel operation.
	//
	// POST /models/{name}/stop
	StopModel(ctx context.Context, params StopModelParams) (*LiveStateResponse, error)
}

// RawHandler handles raw response operations described by OpenAPI v3 specification.
type RawHandler interface {
	// StartTurn implements startTurn operation.
	//
	// Run one agent turn (SSE stream).
	//
	// POST /turn
	StartTurn(ctx context.Context, req *Task, w http.ResponseWriter) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h  Handler
	rh RawHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, rh RawHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		rh:         rh,
		baseServer: s,
	}, nil
}
