// Code generated by ogen, DO NOT EDIT.
package genapi

type CancelTurnRes interface {
	cancelTurnRes()
}

type CommitDocumentRes interface {
	commitDocumentRes()
}

type EvictCorpusDocumentRes interface {
	evictCorpusDocumentRes()
}

type GetSessionMeterRes interface {
	getSessionMeterRes()
}

type GetTurnContextRes interface {
	getTurnContextRes()
}

type ListDirectoryRes interface {
	listDirectoryRes()
}

type PutCorpusRes interface {
	putCorpusRes()
}

type PutSessionContextRes interface {
	putSessionContextRes()
}

type RenameSessionRes interface {
	renameSessionRes()
}

type ResolveLocateRes interface {
	resolveLocateRes()
}

type SaveDocumentRes interface {
	saveDocumentRes()
}

type StartTurnRes interface {
	startTurnRes()
}
