// Code generated by ogen, DO NOT EDIT.

package genapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ApplyEditOperation           OperationName = "ApplyEdit"
	CancelTurnOperation          OperationName = "CancelTurn"
	CommitDocumentOperation      OperationName = "CommitDocument"
	CreateSessionOperation       OperationName = "CreateSession"
	CreateWorkspaceOperation     OperationName = "CreateWorkspace"
	EvictCorpusDocumentOperation OperationName = "EvictCorpusDocument"
	GetBlocksOperation           OperationName = "GetBlocks"
	GetCandidatesOperation       OperationName = "GetCandidates"
	GetCorpusOperation           OperationName = "GetCorpus"
	GetDiffOperation             OperationName = "GetDiff"
	GetFleetOperation            OperationName = "GetFleet"
	GetHealthOperation           OperationName = "GetHealth"
	GetHistoryOperation          OperationName = "GetHistory"
	GetModelStatusOperation      OperationName = "GetModelStatus"
	GetSessionMessagesOperation  OperationName = "GetSessionMessages"
	GetSessionMeterOperation     OperationName = "GetSessionMeter"
	GetTurnContextOperation      OperationName = "GetTurnContext"
	GetWorkspaceOperation        OperationName = "GetWorkspace"
	IndexCorpusOperation         OperationName = "IndexCorpus"
	ListDirectoryOperation       OperationName = "ListDirectory"
	ListModelsOperation          OperationName = "ListModels"
	ListModesOperation           OperationName = "ListModes"
	ListSessionsOperation        OperationName = "ListSessions"
	ListToolsOperation           OperationName = "ListTools"
	ListWorkspacesOperation      OperationName = "ListWorkspaces"
	OpenDocumentOperation        OperationName = "OpenDocument"
	ProvisionModelOperation      OperationName = "ProvisionModel"
	PutCorpusOperation           OperationName = "PutCorpus"
	PutSessionContextOperation   OperationName = "PutSessionContext"
	RenameSessionOperation       OperationName = "RenameSession"
	ResolveLocateOperation       OperationName = "ResolveLocate"
	SaveDocumentOperation        OperationName = "SaveDocument"
	StartModelOperation          OperationName = "StartModel"
	StartTurnOperation           OperationName = "StartTurn"
	StopModelOperation           OperationName = "StopModel"
)
