// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"context"
	"net/http"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ApplyEdit implements applyEdit operation.
	//
	// POST /documents/{id}/edits
	ApplyEdit(ctx context.Context, req *BlockEdit, params ApplyEditParams) (*Revision, error)
	// CommitDocument implements commitDocument operation.
	//
	// Accepts the staged candidates (newest-first, deterministic), re-validates each candidate's base
	// content hash, formats, makes one git commit with an auto-derived message
	// (`mode · blockID · diff`), and mirrors the canonical markdown back to the opened file (ADR-0047
	// §1/§5/§8). An empty accept creates no commit. If the file on disk changed since the engine last
	// read it, the write-through is refused with `file-changed-externally` unless `overwrite` is true —
	// never a silent clobber.
	//
	// POST /documents/{id}/commits
	CommitDocument(ctx context.Context, req OptCommitRequest, params CommitDocumentParams) (CommitDocumentRes, error)
	// CreateSession implements createSession operation.
	//
	// POST /sessions
	CreateSession(ctx context.Context, req *CreateSessionRequest) (*Session, error)
	// CreateWorkspace implements createWorkspace operation.
	//
	// Canonicalizes the root (EvalSymlinks + case-fold): an alias or an already-open nested directory
	// resumes the most specific existing workspace; otherwise a workspace is created and seeded with the
	// root as its first corpus root and `**/*.md` as the default include.
	//
	// POST /workspaces
	CreateWorkspace(ctx context.Context, req *CreateWorkspaceRequest) (*Workspace, error)
	// EvictCorpusDocument implements evictCorpusDocument operation.
	//
	// Removes the file's chunks from both the vector and full-text indexes and records an eviction
	// tombstone (status `evicted` until re-indexed). No file on disk is touched. Deleting twice succeeds.
	//
	// DELETE /corpus/documents/{id}
	EvictCorpusDocument(ctx context.Context, params EvictCorpusDocumentParams) (EvictCorpusDocumentRes, error)
	// GetBlocks implements getBlocks operation.
	//
	// GET /documents/{id}/blocks
	GetBlocks(ctx context.Context, params GetBlocksParams) ([]Block, error)
	// GetCandidates implements getCandidates operation.
	//
	// GET /documents/{id}/blocks/{bid}/candidates
	GetCandidates(ctx context.Context, params GetCandidatesParams) ([]Candidate, error)
	// GetCorpus implements getCorpus operation.
	//
	// Read a workspace's corpus scope, per-document status, and job progress (ADR-0049 §4).
	//
	// GET /corpus
	GetCorpus(ctx context.Context, params GetCorpusParams) (*CorpusState, error)
	// GetDiff implements getDiff operation.
	//
	// GET /documents/{id}/diff
	GetDiff(ctx context.Context, params GetDiffParams) ([]WordEdit, error)
	// GetFleet implements getFleet operation.
	//
	// The observability surface the model selectors consume. Answers 200 even when the control daemon is
	// unreachable: `control` drops to "unreachable" and `models` carries the last-known projection with
	// every liveState forced to "unknown" (ADR-0040 §3).
	//
	// GET /fleet
	GetFleet(ctx context.Context) (*FleetState, error)
	// GetHealth implements getHealth operation.
	//
	// Liveness check.
	//
	// GET /health
	GetHealth(ctx context.Context) (*Health, error)
	// GetHistory implements getHistory operation.
	//
	// GET /documents/{id}/history
	GetHistory(ctx context.Context, params GetHistoryParams) ([]Revision, error)
	// GetModelStatus implements getModelStatus operation.
	//
	// GET /models/{name}/status
	GetModelStatus(ctx context.Context, params GetModelStatusParams) (*LiveStateResponse, error)
	// GetSessionMessages implements getSessionMessages operation.
	//
	// GET /sessions/{id}/messages
	GetSessionMessages(ctx context.Context, params GetSessionMessagesParams) ([]Message, error)
	// GetSessionMeter implements getSessionMeter operation.
	//
	// Aggregates the workspace shard's meter_events for a session by component (system, tools, rag,
	// history, mentions, user, thinking, completion) and returns the cumulative total. The session id is
	// resolved to its workspace shard through the registry's session routing index; an unknown session is
	// a typed 404.
	//
	// GET /sessions/{id}/meter
	GetSessionMeter(ctx context.Context, params GetSessionMeterParams) (GetSessionMeterRes, error)
	// GetTurnContext implements getTurnContext operation.
	//
	// Returns the context snapshot the engine persisted for a turn: every assembled message with its
	// component and provenance, the retrieved chunks, the labeled drops, and the budget accounting. The
	// snapshot is engine data; clients render it and never reconstruct it. The turn id is resolved to its
	// workspace shard through the registry's turn routing index; an unknown turn is a typed 404.
	//
	// GET /turns/{id}/context
	GetTurnContext(ctx context.Context, params GetTurnContextParams) (GetTurnContextRes, error)
	// GetWorkspace implements getWorkspace operation.
	//
	// Read one workspace record.
	//
	// GET /workspaces/{id}
	GetWorkspace(ctx context.Context, params GetWorkspaceParams) (*Workspace, error)
	// IndexCorpus implements indexCorpus operation.
	//
	// Bulk (re)index the current scope; async, idempotent per unchanged content (ADR-0049 §4).
	//
	// POST /corpus/index
	IndexCorpus(ctx context.Context, req *CorpusIndexRequest) (*CorpusJob, error)
	// ListDirectory implements listDirectory operation.
	//
	// Bounded by ALLOWED_ROOTS (ADR-0049 §6): a path outside the allowlist is refused with the typed
	// `path-outside-allowed-roots` error, never silently.
	//
	// GET /directories
	ListDirectory(ctx context.Context, params ListDirectoryParams) (ListDirectoryRes, error)
	// ListModels implements listModels operation.
	//
	// Deprecated for clients — use /fleet (ADR-0040). Retained for compatibility.
	//
	// GET /models
	ListModels(ctx context.Context) ([]Model, error)
	// ListModes implements listModes operation.
	//
	// GET /modes
	ListModes(ctx context.Context) ([]Mode, error)
	// ListSessions implements listSessions operation.
	//
	// Lists sessions newest-first. At least one of `workspaceId` or `documentId` is required:
	// `workspaceId` selects the workspace shard directly; `documentId` resolves the workspace that
	// contains the document (fallback). Both filters may be combined.
	//
	// GET /sessions
	ListSessions(ctx context.Context, params ListSessionsParams) ([]Session, error)
	// ListTools implements listTools operation.
	//
	// GET /tools
	ListTools(ctx context.Context) ([]ToolDef, error)
	// ListWorkspaces implements listWorkspaces operation.
	//
	// List the workspace registry (ADR-0049 §2).
	//
	// GET /workspaces
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	// OpenDocument implements openDocument operation.
	//
	// Open/create a document by path; returns its surrogate id.
	//
	// POST /documents
	OpenDocument(ctx context.Context, req *OpenDocumentRequest) (*Document, error)
	// ProvisionModel implements provisionModel operation.
	//
	// POST /models/{name}/provision
	ProvisionModel(ctx context.Context, params ProvisionModelParams) (*ProvisionResponse, error)
	// PutCorpus implements putCorpus operation.
	//
	// Roots are canonicalized and deduped; include/exclude globs decide retrievability (default `**/*.md`,
	// hidden directories excluded). The scope change reconciles the index asynchronously; no document file
	// is ever created, modified, or deleted. A root outside ALLOWED_ROOTS is refused with the typed
	// `path-outside-allowed-roots`.
	//
	// PUT /corpus
	PutCorpus(ctx context.Context, req *PutCorpusRequest) (PutCorpusRes, error)
	// PutSessionContext implements putSessionContext operation.
	//
	// Replaces the session's persisted context policy (pins, excludes, auto-RAG flag, retrieval query) and
	// returns the session so the client reads back what was persisted. The policy carries the same shape
	// as the per-turn `Task.context` override; it survives turns, reconnects, and session resume. Per-turn
	// overrides are never persisted. An unknown session is the typed 404.
	//
	// PUT /sessions/{id}/context
	PutSessionContext(ctx context.Context, req *ContextPolicy, params PutSessionContextParams) (PutSessionContextRes, error)
	// ResolveLocate implements resolveLocate operation.
	//
	// When a `/locate` turn resolves to a fuzzy match it emits a `locate` event with ranked candidates and
	// waits (bounded) for the user's choice. This route resumes the turn: pick a candidate by its
	// `chunkKey`, or cancel to degrade the turn to plain chat. No model call and no edit happen before the
	// choice. An unknown turn id is a typed 404; a turn that is not waiting on a picker (already answered,
	// timed out, or never ambiguous) is a typed 409.
	//
	// POST /turns/{id}/locate
	ResolveLocate(ctx context.Context, req *LocateChoice, params ResolveLocateParams) (ResolveLocateRes, error)
	// SaveDocument implements saveDocument operation.
	//
	// The manual-edit wire path (ADR-0038): the client's whole block-tree snapshot. Array order =
	// position; a block with no `id` is new (the engine mints a UUID, ADR-0020 §3); an `id` present in
	// the current tree but absent from the request is deleted; a changed `kind`/`parentId` is
	// retyped/moved. The engine reconciles, normalizes on write and formats on commit, and commits
	// `autosave @ <ts>` iff anything changed (a no-op returns the current HEAD). A manual save of a block
	// drops its open candidates. When `writeThrough` is true (explicit Save / Cmd+S, not the periodic
	// autosave), the engine also mirrors the canonical markdown back to the opened file path (ADR-0039).
	// Per ADR-0047 §4 a no-op save still re-syncs a stale disk (no new commit), and an external change
	// surfaces as a `file-changed-externally` conflict — never a silent clobber.
	//
	// PUT /documents/{id}/tree
	SaveDocument(ctx context.Context, req *SaveTreeRequest, params SaveDocumentParams) (SaveDocumentRes, error)
	// StartModel implements startModel operation.
	//
	// POST /models/{name}/start
	StartModel(ctx context.Context, params StartModelParams) (*LiveStateResponse, error)
	// StopModel implements stopModel operation.
	//
	// POST /models/{name}/stop
	StopModel(ctx context.Context, params StopModelParams) (*LiveStateResponse, error)
}

// RawHandler handles raw response operations described by OpenAPI v3 specification.
type RawHandler interface {
	// StartTurn implements startTurn operation.
	//
	// Run one agent turn (SSE stream).
	//
	// POST /turn
	StartTurn(ctx context.Context, req *Task, w http.ResponseWriter) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h  Handler
	rh RawHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, rh RawHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		rh:         rh,
		baseServer: s,
	}, nil
}
