// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"net/http"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Block
type Block struct {
	ID       string    `json:"id"`
	ParentId OptString `json:"parentId"`
	Kind     BlockKind `json:"kind"`
	Position int       `json:"position"`
	Text     string    `json:"text"`
	Hash     OptString `json:"hash"`
}

// GetID returns the value of ID.
func (s *Block) GetID() string {
	return s.ID
}

// GetParentId returns the value of ParentId.
func (s *Block) GetParentId() OptString {
	return s.ParentId
}

// GetKind returns the value of Kind.
func (s *Block) GetKind() BlockKind {
	return s.Kind
}

// GetPosition returns the value of Position.
func (s *Block) GetPosition() int {
	return s.Position
}

// GetText returns the value of Text.
func (s *Block) GetText() string {
	return s.Text
}

// GetHash returns the value of Hash.
func (s *Block) GetHash() OptString {
	return s.Hash
}

// SetID sets the value of ID.
func (s *Block) SetID(val string) {
	s.ID = val
}

// SetParentId sets the value of ParentId.
func (s *Block) SetParentId(val OptString) {
	s.ParentId = val
}

// SetKind sets the value of Kind.
func (s *Block) SetKind(val BlockKind) {
	s.Kind = val
}

// SetPosition sets the value of Position.
func (s *Block) SetPosition(val int) {
	s.Position = val
}

// SetText sets the value of Text.
func (s *Block) SetText(val string) {
	s.Text = val
}

// SetHash sets the value of Hash.
func (s *Block) SetHash(val OptString) {
	s.Hash = val
}

// Ref: #/components/schemas/BlockEdit
type BlockEdit struct {
	BlockId string  `json:"blockId"`
	Text    string  `json:"text"`
	Guards  []Guard `json:"guards"`
}

// GetBlockId returns the value of BlockId.
func (s *BlockEdit) GetBlockId() string {
	return s.BlockId
}

// GetText returns the value of Text.
func (s *BlockEdit) GetText() string {
	return s.Text
}

// GetGuards returns the value of Guards.
func (s *BlockEdit) GetGuards() []Guard {
	return s.Guards
}

// SetBlockId sets the value of BlockId.
func (s *BlockEdit) SetBlockId(val string) {
	s.BlockId = val
}

// SetText sets the value of Text.
func (s *BlockEdit) SetText(val string) {
	s.Text = val
}

// SetGuards sets the value of Guards.
func (s *BlockEdit) SetGuards(val []Guard) {
	s.Guards = val
}

type BlockKind string

const (
	BlockKindParagraph  BlockKind = "paragraph"
	BlockKindHeading    BlockKind = "heading"
	BlockKindListItem   BlockKind = "list_item"
	BlockKindCodeFence  BlockKind = "code_fence"
	BlockKindBlockquote BlockKind = "blockquote"
	BlockKindTable      BlockKind = "table"
)

// AllValues returns all BlockKind values.
func (BlockKind) AllValues() []BlockKind {
	return []BlockKind{
		BlockKindParagraph,
		BlockKindHeading,
		BlockKindListItem,
		BlockKindCodeFence,
		BlockKindBlockquote,
		BlockKindTable,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BlockKind) MarshalText() ([]byte, error) {
	switch s {
	case BlockKindParagraph:
		return []byte(s), nil
	case BlockKindHeading:
		return []byte(s), nil
	case BlockKindListItem:
		return []byte(s), nil
	case BlockKindCodeFence:
		return []byte(s), nil
	case BlockKindBlockquote:
		return []byte(s), nil
	case BlockKindTable:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BlockKind) UnmarshalText(data []byte) error {
	switch BlockKind(data) {
	case BlockKindParagraph:
		*s = BlockKindParagraph
		return nil
	case BlockKindHeading:
		*s = BlockKindHeading
		return nil
	case BlockKindListItem:
		*s = BlockKindListItem
		return nil
	case BlockKindCodeFence:
		*s = BlockKindCodeFence
		return nil
	case BlockKindBlockquote:
		*s = BlockKindBlockquote
		return nil
	case BlockKindTable:
		*s = BlockKindTable
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Candidate
type Candidate struct {
	BlockId OptString `json:"blockId"`
	Text    OptString `json:"text"`
	BaseId  OptString `json:"baseId"`
}

// GetBlockId returns the value of BlockId.
func (s *Candidate) GetBlockId() OptString {
	return s.BlockId
}

// GetText returns the value of Text.
func (s *Candidate) GetText() OptString {
	return s.Text
}

// GetBaseId returns the value of BaseId.
func (s *Candidate) GetBaseId() OptString {
	return s.BaseId
}

// SetBlockId sets the value of BlockId.
func (s *Candidate) SetBlockId(val OptString) {
	s.BlockId = val
}

// SetText sets the value of Text.
func (s *Candidate) SetText(val OptString) {
	s.Text = val
}

// SetBaseId sets the value of BaseId.
func (s *Candidate) SetBaseId(val OptString) {
	s.BaseId = val
}

// Ref: #/components/schemas/Capabilities
type Capabilities struct {
	ContextLength        int  `json:"contextLength"`
	ThinkingMode         bool `json:"thinkingMode"`
	SupportsSystemPrompt bool `json:"supportsSystemPrompt"`
}

// GetContextLength returns the value of ContextLength.
func (s *Capabilities) GetContextLength() int {
	return s.ContextLength
}

// GetThinkingMode returns the value of ThinkingMode.
func (s *Capabilities) GetThinkingMode() bool {
	return s.ThinkingMode
}

// GetSupportsSystemPrompt returns the value of SupportsSystemPrompt.
func (s *Capabilities) GetSupportsSystemPrompt() bool {
	return s.SupportsSystemPrompt
}

// SetContextLength sets the value of ContextLength.
func (s *Capabilities) SetContextLength(val int) {
	s.ContextLength = val
}

// SetThinkingMode sets the value of ThinkingMode.
func (s *Capabilities) SetThinkingMode(val bool) {
	s.ThinkingMode = val
}

// SetSupportsSystemPrompt sets the value of SupportsSystemPrompt.
func (s *Capabilities) SetSupportsSystemPrompt(val bool) {
	s.SupportsSystemPrompt = val
}

// Ref: #/components/schemas/CreateSessionRequest
type CreateSessionRequest struct {
	DocumentId    string    `json:"documentId"`
	AnchorBlockId OptString `json:"anchorBlockId"`
	ModeType      OptString `json:"modeType"`
}

// GetDocumentId returns the value of DocumentId.
func (s *CreateSessionRequest) GetDocumentId() string {
	return s.DocumentId
}

// GetAnchorBlockId returns the value of AnchorBlockId.
func (s *CreateSessionRequest) GetAnchorBlockId() OptString {
	return s.AnchorBlockId
}

// GetModeType returns the value of ModeType.
func (s *CreateSessionRequest) GetModeType() OptString {
	return s.ModeType
}

// SetDocumentId sets the value of DocumentId.
func (s *CreateSessionRequest) SetDocumentId(val string) {
	s.DocumentId = val
}

// SetAnchorBlockId sets the value of AnchorBlockId.
func (s *CreateSessionRequest) SetAnchorBlockId(val OptString) {
	s.AnchorBlockId = val
}

// SetModeType sets the value of ModeType.
func (s *CreateSessionRequest) SetModeType(val OptString) {
	s.ModeType = val
}

// Ref: #/components/schemas/Document
type Document struct {
	ID          string   `json:"id"`
	Path        string   `json:"path"`
	RootBlockId string   `json:"rootBlockId"`
	UpdatedAt   OptInt64 `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Document) GetID() string {
	return s.ID
}

// GetPath returns the value of Path.
func (s *Document) GetPath() string {
	return s.Path
}

// GetRootBlockId returns the value of RootBlockId.
func (s *Document) GetRootBlockId() string {
	return s.RootBlockId
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Document) GetUpdatedAt() OptInt64 {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Document) SetID(val string) {
	s.ID = val
}

// SetPath sets the value of Path.
func (s *Document) SetPath(val string) {
	s.Path = val
}

// SetRootBlockId sets the value of RootBlockId.
func (s *Document) SetRootBlockId(val string) {
	s.RootBlockId = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Document) SetUpdatedAt(val OptInt64) {
	s.UpdatedAt = val
}

// Framing marker for the SSE stream: the `event:` line carries `type`; the `data:` line carries the
// payload schema matching that type. The payload JSON itself has no `type` field.
// Ref: #/components/schemas/Event
type Event struct {
	Type EventType `json:"type"`
}

// GetType returns the value of Type.
func (s *Event) GetType() EventType {
	return s.Type
}

// SetType sets the value of Type.
func (s *Event) SetType(val EventType) {
	s.Type = val
}

type EventType string

const (
	EventTypeToken        EventType = "token"
	EventTypeMeter        EventType = "meter"
	EventTypeCandidate    EventType = "candidate"
	EventTypeDiff         EventType = "diff"
	EventTypeRag          EventType = "rag"
	EventTypeDone         EventType = "done"
	EventTypeError        EventType = "error"
	EventTypeBackpressure EventType = "backpressure"
)

// AllValues returns all EventType values.
func (EventType) AllValues() []EventType {
	return []EventType{
		EventTypeToken,
		EventTypeMeter,
		EventTypeCandidate,
		EventTypeDiff,
		EventTypeRag,
		EventTypeDone,
		EventTypeError,
		EventTypeBackpressure,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EventType) MarshalText() ([]byte, error) {
	switch s {
	case EventTypeToken:
		return []byte(s), nil
	case EventTypeMeter:
		return []byte(s), nil
	case EventTypeCandidate:
		return []byte(s), nil
	case EventTypeDiff:
		return []byte(s), nil
	case EventTypeRag:
		return []byte(s), nil
	case EventTypeDone:
		return []byte(s), nil
	case EventTypeError:
		return []byte(s), nil
	case EventTypeBackpressure:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EventType) UnmarshalText(data []byte) error {
	switch EventType(data) {
	case EventTypeToken:
		*s = EventTypeToken
		return nil
	case EventTypeMeter:
		*s = EventTypeMeter
		return nil
	case EventTypeCandidate:
		*s = EventTypeCandidate
		return nil
	case EventTypeDiff:
		*s = EventTypeDiff
		return nil
	case EventTypeRag:
		*s = EventTypeRag
		return nil
	case EventTypeDone:
		*s = EventTypeDone
		return nil
	case EventTypeError:
		*s = EventTypeError
		return nil
	case EventTypeBackpressure:
		*s = EventTypeBackpressure
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Guard
type Guard struct {
	BlockId string `json:"blockId"`
	Hash    string `json:"hash"`
}

// GetBlockId returns the value of BlockId.
func (s *Guard) GetBlockId() string {
	return s.BlockId
}

// GetHash returns the value of Hash.
func (s *Guard) GetHash() string {
	return s.Hash
}

// SetBlockId sets the value of BlockId.
func (s *Guard) SetBlockId(val string) {
	s.BlockId = val
}

// SetHash sets the value of Hash.
func (s *Guard) SetHash(val string) {
	s.Hash = val
}

// Ref: #/components/schemas/Health
type Health struct {
	Status HealthStatus `json:"status"`
	// The engine's actual bound base URL (http://host:port). Populated so a dynamic-port client (ADR-0021
	// §1) can discover the engine rather than assume a port. In fixed mode this equals the configured
	// address; in dynamic mode it is the OS-assigned port. Recorded amendment to ADR-0017 §4.
	BaseUrl OptString `json:"baseUrl"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// GetBaseUrl returns the value of BaseUrl.
func (s *Health) GetBaseUrl() OptString {
	return s.BaseUrl
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetBaseUrl sets the value of BaseUrl.
func (s *Health) SetBaseUrl(val OptString) {
	s.BaseUrl = val
}

type HealthStatus string

const (
	HealthStatusOk HealthStatus = "ok"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/LiveStateResponse
type LiveStateResponse struct {
	Name  string                 `json:"name"`
	State LiveStateResponseState `json:"state"`
}

// GetName returns the value of Name.
func (s *LiveStateResponse) GetName() string {
	return s.Name
}

// GetState returns the value of State.
func (s *LiveStateResponse) GetState() LiveStateResponseState {
	return s.State
}

// SetName sets the value of Name.
func (s *LiveStateResponse) SetName(val string) {
	s.Name = val
}

// SetState sets the value of State.
func (s *LiveStateResponse) SetState(val LiveStateResponseState) {
	s.State = val
}

type LiveStateResponseState string

const (
	LiveStateResponseStateUp           LiveStateResponseState = "up"
	LiveStateResponseStateDown         LiveStateResponseState = "down"
	LiveStateResponseStateStarting     LiveStateResponseState = "starting"
	LiveStateResponseStateStopping     LiveStateResponseState = "stopping"
	LiveStateResponseStateProvisioning LiveStateResponseState = "provisioning"
	LiveStateResponseStateUnknown      LiveStateResponseState = "unknown"
)

// AllValues returns all LiveStateResponseState values.
func (LiveStateResponseState) AllValues() []LiveStateResponseState {
	return []LiveStateResponseState{
		LiveStateResponseStateUp,
		LiveStateResponseStateDown,
		LiveStateResponseStateStarting,
		LiveStateResponseStateStopping,
		LiveStateResponseStateProvisioning,
		LiveStateResponseStateUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s LiveStateResponseState) MarshalText() ([]byte, error) {
	switch s {
	case LiveStateResponseStateUp:
		return []byte(s), nil
	case LiveStateResponseStateDown:
		return []byte(s), nil
	case LiveStateResponseStateStarting:
		return []byte(s), nil
	case LiveStateResponseStateStopping:
		return []byte(s), nil
	case LiveStateResponseStateProvisioning:
		return []byte(s), nil
	case LiveStateResponseStateUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *LiveStateResponseState) UnmarshalText(data []byte) error {
	switch LiveStateResponseState(data) {
	case LiveStateResponseStateUp:
		*s = LiveStateResponseStateUp
		return nil
	case LiveStateResponseStateDown:
		*s = LiveStateResponseStateDown
		return nil
	case LiveStateResponseStateStarting:
		*s = LiveStateResponseStateStarting
		return nil
	case LiveStateResponseStateStopping:
		*s = LiveStateResponseStateStopping
		return nil
	case LiveStateResponseStateProvisioning:
		*s = LiveStateResponseStateProvisioning
		return nil
	case LiveStateResponseStateUnknown:
		*s = LiveStateResponseStateUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Message
type Message struct {
	Role      MessageRole `json:"role"`
	Content   string      `json:"content"`
	Timestamp OptInt64    `json:"timestamp"`
}

// GetRole returns the value of Role.
func (s *Message) GetRole() MessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *Message) GetContent() string {
	return s.Content
}

// GetTimestamp returns the value of Timestamp.
func (s *Message) GetTimestamp() OptInt64 {
	return s.Timestamp
}

// SetRole sets the value of Role.
func (s *Message) SetRole(val MessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *Message) SetContent(val string) {
	s.Content = val
}

// SetTimestamp sets the value of Timestamp.
func (s *Message) SetTimestamp(val OptInt64) {
	s.Timestamp = val
}

type MessageRole string

const (
	MessageRoleUser      MessageRole = "user"
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleTool      MessageRole = "tool"
)

// AllValues returns all MessageRole values.
func (MessageRole) AllValues() []MessageRole {
	return []MessageRole{
		MessageRoleUser,
		MessageRoleAssistant,
		MessageRoleTool,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MessageRole) MarshalText() ([]byte, error) {
	switch s {
	case MessageRoleUser:
		return []byte(s), nil
	case MessageRoleAssistant:
		return []byte(s), nil
	case MessageRoleTool:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MessageRole) UnmarshalText(data []byte) error {
	switch MessageRole(data) {
	case MessageRoleUser:
		*s = MessageRoleUser
		return nil
	case MessageRoleAssistant:
		*s = MessageRoleAssistant
		return nil
	case MessageRoleTool:
		*s = MessageRoleTool
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Mode
type Mode struct {
	Name          string             `json:"name"`
	SystemPrompt  OptString          `json:"systemPrompt"`
	DefaultModel  OptString          `json:"defaultModel"`
	ToolAllowlist []string           `json:"toolAllowlist"`
	Params        OptSamplingParams  `json:"params"`
	MaxSteps      OptInt             `json:"maxSteps"`
	Agentic       OptBool            `json:"agentic"`
	Kind          OptString          `json:"kind"`
	Preamble      OptString          `json:"preamble"`
	ToolCalling   OptModeToolCalling `json:"toolCalling"`
}

// GetName returns the value of Name.
func (s *Mode) GetName() string {
	return s.Name
}

// GetSystemPrompt returns the value of SystemPrompt.
func (s *Mode) GetSystemPrompt() OptString {
	return s.SystemPrompt
}

// GetDefaultModel returns the value of DefaultModel.
func (s *Mode) GetDefaultModel() OptString {
	return s.DefaultModel
}

// GetToolAllowlist returns the value of ToolAllowlist.
func (s *Mode) GetToolAllowlist() []string {
	return s.ToolAllowlist
}

// GetParams returns the value of Params.
func (s *Mode) GetParams() OptSamplingParams {
	return s.Params
}

// GetMaxSteps returns the value of MaxSteps.
func (s *Mode) GetMaxSteps() OptInt {
	return s.MaxSteps
}

// GetAgentic returns the value of Agentic.
func (s *Mode) GetAgentic() OptBool {
	return s.Agentic
}

// GetKind returns the value of Kind.
func (s *Mode) GetKind() OptString {
	return s.Kind
}

// GetPreamble returns the value of Preamble.
func (s *Mode) GetPreamble() OptString {
	return s.Preamble
}

// GetToolCalling returns the value of ToolCalling.
func (s *Mode) GetToolCalling() OptModeToolCalling {
	return s.ToolCalling
}

// SetName sets the value of Name.
func (s *Mode) SetName(val string) {
	s.Name = val
}

// SetSystemPrompt sets the value of SystemPrompt.
func (s *Mode) SetSystemPrompt(val OptString) {
	s.SystemPrompt = val
}

// SetDefaultModel sets the value of DefaultModel.
func (s *Mode) SetDefaultModel(val OptString) {
	s.DefaultModel = val
}

// SetToolAllowlist sets the value of ToolAllowlist.
func (s *Mode) SetToolAllowlist(val []string) {
	s.ToolAllowlist = val
}

// SetParams sets the value of Params.
func (s *Mode) SetParams(val OptSamplingParams) {
	s.Params = val
}

// SetMaxSteps sets the value of MaxSteps.
func (s *Mode) SetMaxSteps(val OptInt) {
	s.MaxSteps = val
}

// SetAgentic sets the value of Agentic.
func (s *Mode) SetAgentic(val OptBool) {
	s.Agentic = val
}

// SetKind sets the value of Kind.
func (s *Mode) SetKind(val OptString) {
	s.Kind = val
}

// SetPreamble sets the value of Preamble.
func (s *Mode) SetPreamble(val OptString) {
	s.Preamble = val
}

// SetToolCalling sets the value of ToolCalling.
func (s *Mode) SetToolCalling(val OptModeToolCalling) {
	s.ToolCalling = val
}

type ModeToolCalling string

const (
	ModeToolCallingNative ModeToolCalling = "native"
	ModeToolCallingRouter ModeToolCalling = "router"
)

// AllValues returns all ModeToolCalling values.
func (ModeToolCalling) AllValues() []ModeToolCalling {
	return []ModeToolCalling{
		ModeToolCallingNative,
		ModeToolCallingRouter,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ModeToolCalling) MarshalText() ([]byte, error) {
	switch s {
	case ModeToolCallingNative:
		return []byte(s), nil
	case ModeToolCallingRouter:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ModeToolCalling) UnmarshalText(data []byte) error {
	switch ModeToolCalling(data) {
	case ModeToolCallingNative:
		*s = ModeToolCallingNative
		return nil
	case ModeToolCallingRouter:
		*s = ModeToolCallingRouter
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Model
type Model struct {
	Name         string            `json:"name"`
	BaseUrl      string            `json:"baseUrl"`
	Capabilities OptCapabilities   `json:"capabilities"`
	ModeTags     []string          `json:"modeTags"`
	LiveState    OptModelLiveState `json:"liveState"`
}

// GetName returns the value of Name.
func (s *Model) GetName() string {
	return s.Name
}

// GetBaseUrl returns the value of BaseUrl.
func (s *Model) GetBaseUrl() string {
	return s.BaseUrl
}

// GetCapabilities returns the value of Capabilities.
func (s *Model) GetCapabilities() OptCapabilities {
	return s.Capabilities
}

// GetModeTags returns the value of ModeTags.
func (s *Model) GetModeTags() []string {
	return s.ModeTags
}

// GetLiveState returns the value of LiveState.
func (s *Model) GetLiveState() OptModelLiveState {
	return s.LiveState
}

// SetName sets the value of Name.
func (s *Model) SetName(val string) {
	s.Name = val
}

// SetBaseUrl sets the value of BaseUrl.
func (s *Model) SetBaseUrl(val string) {
	s.BaseUrl = val
}

// SetCapabilities sets the value of Capabilities.
func (s *Model) SetCapabilities(val OptCapabilities) {
	s.Capabilities = val
}

// SetModeTags sets the value of ModeTags.
func (s *Model) SetModeTags(val []string) {
	s.ModeTags = val
}

// SetLiveState sets the value of LiveState.
func (s *Model) SetLiveState(val OptModelLiveState) {
	s.LiveState = val
}

type ModelLiveState string

const (
	ModelLiveStateUp           ModelLiveState = "up"
	ModelLiveStateDown         ModelLiveState = "down"
	ModelLiveStateStarting     ModelLiveState = "starting"
	ModelLiveStateStopping     ModelLiveState = "stopping"
	ModelLiveStateProvisioning ModelLiveState = "provisioning"
	ModelLiveStateUnknown      ModelLiveState = "unknown"
)

// AllValues returns all ModelLiveState values.
func (ModelLiveState) AllValues() []ModelLiveState {
	return []ModelLiveState{
		ModelLiveStateUp,
		ModelLiveStateDown,
		ModelLiveStateStarting,
		ModelLiveStateStopping,
		ModelLiveStateProvisioning,
		ModelLiveStateUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ModelLiveState) MarshalText() ([]byte, error) {
	switch s {
	case ModelLiveStateUp:
		return []byte(s), nil
	case ModelLiveStateDown:
		return []byte(s), nil
	case ModelLiveStateStarting:
		return []byte(s), nil
	case ModelLiveStateStopping:
		return []byte(s), nil
	case ModelLiveStateProvisioning:
		return []byte(s), nil
	case ModelLiveStateUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ModelLiveState) UnmarshalText(data []byte) error {
	switch ModelLiveState(data) {
	case ModelLiveStateUp:
		*s = ModelLiveStateUp
		return nil
	case ModelLiveStateDown:
		*s = ModelLiveStateDown
		return nil
	case ModelLiveStateStarting:
		*s = ModelLiveStateStarting
		return nil
	case ModelLiveStateStopping:
		*s = ModelLiveStateStopping
		return nil
	case ModelLiveStateProvisioning:
		*s = ModelLiveStateProvisioning
		return nil
	case ModelLiveStateUnknown:
		*s = ModelLiveStateUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/OpenDocumentRequest
type OpenDocumentRequest struct {
	Path string `json:"path"`
}

// GetPath returns the value of Path.
func (s *OpenDocumentRequest) GetPath() string {
	return s.Path
}

// SetPath sets the value of Path.
func (s *OpenDocumentRequest) SetPath(val string) {
	s.Path = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCapabilities returns new OptCapabilities with value set to v.
func NewOptCapabilities(v Capabilities) OptCapabilities {
	return OptCapabilities{
		Value: v,
		Set:   true,
	}
}

// OptCapabilities is optional Capabilities.
type OptCapabilities struct {
	Value Capabilities
	Set   bool
}

// IsSet returns true if OptCapabilities was set.
func (o OptCapabilities) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCapabilities) Reset() {
	var v Capabilities
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCapabilities) SetTo(v Capabilities) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCapabilities) Get() (v Capabilities, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCapabilities) Or(d Capabilities) Capabilities {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptModeToolCalling returns new OptModeToolCalling with value set to v.
func NewOptModeToolCalling(v ModeToolCalling) OptModeToolCalling {
	return OptModeToolCalling{
		Value: v,
		Set:   true,
	}
}

// OptModeToolCalling is optional ModeToolCalling.
type OptModeToolCalling struct {
	Value ModeToolCalling
	Set   bool
}

// IsSet returns true if OptModeToolCalling was set.
func (o OptModeToolCalling) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptModeToolCalling) Reset() {
	var v ModeToolCalling
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptModeToolCalling) SetTo(v ModeToolCalling) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptModeToolCalling) Get() (v ModeToolCalling, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptModeToolCalling) Or(d ModeToolCalling) ModeToolCalling {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptModelLiveState returns new OptModelLiveState with value set to v.
func NewOptModelLiveState(v ModelLiveState) OptModelLiveState {
	return OptModelLiveState{
		Value: v,
		Set:   true,
	}
}

// OptModelLiveState is optional ModelLiveState.
type OptModelLiveState struct {
	Value ModelLiveState
	Set   bool
}

// IsSet returns true if OptModelLiveState was set.
func (o OptModelLiveState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptModelLiveState) Reset() {
	var v ModelLiveState
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptModelLiveState) SetTo(v ModelLiveState) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptModelLiveState) Get() (v ModelLiveState, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptModelLiveState) Or(d ModelLiveState) ModelLiveState {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSamplingParams returns new OptSamplingParams with value set to v.
func NewOptSamplingParams(v SamplingParams) OptSamplingParams {
	return OptSamplingParams{
		Value: v,
		Set:   true,
	}
}

// OptSamplingParams is optional SamplingParams.
type OptSamplingParams struct {
	Value SamplingParams
	Set   bool
}

// IsSet returns true if OptSamplingParams was set.
func (o OptSamplingParams) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSamplingParams) Reset() {
	var v SamplingParams
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSamplingParams) SetTo(v SamplingParams) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSamplingParams) Get() (v SamplingParams, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSamplingParams) Or(d SamplingParams) SamplingParams {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSelection returns new OptSelection with value set to v.
func NewOptSelection(v Selection) OptSelection {
	return OptSelection{
		Value: v,
		Set:   true,
	}
}

// OptSelection is optional Selection.
type OptSelection struct {
	Value Selection
	Set   bool
}

// IsSet returns true if OptSelection was set.
func (o OptSelection) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSelection) Reset() {
	var v Selection
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSelection) SetTo(v Selection) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSelection) Get() (v Selection, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSelection) Or(d Selection) Selection {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTurnOptions returns new OptTurnOptions with value set to v.
func NewOptTurnOptions(v TurnOptions) OptTurnOptions {
	return OptTurnOptions{
		Value: v,
		Set:   true,
	}
}

// OptTurnOptions is optional TurnOptions.
type OptTurnOptions struct {
	Value TurnOptions
	Set   bool
}

// IsSet returns true if OptTurnOptions was set.
func (o OptTurnOptions) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTurnOptions) Reset() {
	var v TurnOptions
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTurnOptions) SetTo(v TurnOptions) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTurnOptions) Get() (v TurnOptions, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTurnOptions) Or(d TurnOptions) TurnOptions {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ProvisionResponse
type ProvisionResponse struct {
	ProvisionID string `json:"provisionID"`
}

// GetProvisionID returns the value of ProvisionID.
func (s *ProvisionResponse) GetProvisionID() string {
	return s.ProvisionID
}

// SetProvisionID sets the value of ProvisionID.
func (s *ProvisionResponse) SetProvisionID(val string) {
	s.ProvisionID = val
}

// Ref: #/components/schemas/Revision
type Revision struct {
	ID        OptString `json:"id"`
	Message   OptString `json:"message"`
	Timestamp OptInt64  `json:"timestamp"`
}

// GetID returns the value of ID.
func (s *Revision) GetID() OptString {
	return s.ID
}

// GetMessage returns the value of Message.
func (s *Revision) GetMessage() OptString {
	return s.Message
}

// GetTimestamp returns the value of Timestamp.
func (s *Revision) GetTimestamp() OptInt64 {
	return s.Timestamp
}

// SetID sets the value of ID.
func (s *Revision) SetID(val OptString) {
	s.ID = val
}

// SetMessage sets the value of Message.
func (s *Revision) SetMessage(val OptString) {
	s.Message = val
}

// SetTimestamp sets the value of Timestamp.
func (s *Revision) SetTimestamp(val OptInt64) {
	s.Timestamp = val
}

// Ref: #/components/schemas/SamplingParams
type SamplingParams struct {
	Temperature OptFloat64 `json:"temperature"`
	MaxTokens   OptInt     `json:"maxTokens"`
}

// GetTemperature returns the value of Temperature.
func (s *SamplingParams) GetTemperature() OptFloat64 {
	return s.Temperature
}

// GetMaxTokens returns the value of MaxTokens.
func (s *SamplingParams) GetMaxTokens() OptInt {
	return s.MaxTokens
}

// SetTemperature sets the value of Temperature.
func (s *SamplingParams) SetTemperature(val OptFloat64) {
	s.Temperature = val
}

// SetMaxTokens sets the value of MaxTokens.
func (s *SamplingParams) SetMaxTokens(val OptInt) {
	s.MaxTokens = val
}

// Ref: #/components/schemas/Selection
type Selection struct {
	BlockId OptString `json:"blockId"`
}

// GetBlockId returns the value of BlockId.
func (s *Selection) GetBlockId() OptString {
	return s.BlockId
}

// SetBlockId sets the value of BlockId.
func (s *Selection) SetBlockId(val OptString) {
	s.BlockId = val
}

// Ref: #/components/schemas/Session
type Session struct {
	ID            string    `json:"id"`
	DocumentId    string    `json:"documentId"`
	AnchorBlockId OptString `json:"anchorBlockId"`
	ModeType      OptString `json:"modeType"`
	Title         OptString `json:"title"`
	TokenBudget   OptInt    `json:"tokenBudget"`
	CreatedAt     OptInt64  `json:"createdAt"`
	UpdatedAt     OptInt64  `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Session) GetID() string {
	return s.ID
}

// GetDocumentId returns the value of DocumentId.
func (s *Session) GetDocumentId() string {
	return s.DocumentId
}

// GetAnchorBlockId returns the value of AnchorBlockId.
func (s *Session) GetAnchorBlockId() OptString {
	return s.AnchorBlockId
}

// GetModeType returns the value of ModeType.
func (s *Session) GetModeType() OptString {
	return s.ModeType
}

// GetTitle returns the value of Title.
func (s *Session) GetTitle() OptString {
	return s.Title
}

// GetTokenBudget returns the value of TokenBudget.
func (s *Session) GetTokenBudget() OptInt {
	return s.TokenBudget
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Session) GetCreatedAt() OptInt64 {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Session) GetUpdatedAt() OptInt64 {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Session) SetID(val string) {
	s.ID = val
}

// SetDocumentId sets the value of DocumentId.
func (s *Session) SetDocumentId(val string) {
	s.DocumentId = val
}

// SetAnchorBlockId sets the value of AnchorBlockId.
func (s *Session) SetAnchorBlockId(val OptString) {
	s.AnchorBlockId = val
}

// SetModeType sets the value of ModeType.
func (s *Session) SetModeType(val OptString) {
	s.ModeType = val
}

// SetTitle sets the value of Title.
func (s *Session) SetTitle(val OptString) {
	s.Title = val
}

// SetTokenBudget sets the value of TokenBudget.
func (s *Session) SetTokenBudget(val OptInt) {
	s.TokenBudget = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Session) SetCreatedAt(val OptInt64) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Session) SetUpdatedAt(val OptInt64) {
	s.UpdatedAt = val
}

// StartTurnOKRawTextEventStream represents raw HTTP response for StartTurn text/event-stream.
type StartTurnOKRawTextEventStream struct {
	Response *http.Response `json:"-"`
}

// GetResponse returns the value of Response.
func (s *StartTurnOKRawTextEventStream) GetResponse() *http.Response {
	return s.Response
}

// SetResponse sets the value of Response.
func (s *StartTurnOKRawTextEventStream) SetResponse(val *http.Response) {
	s.Response = val
}

func (*StartTurnOKRawTextEventStream) startTurnRes() {}

// Ref: #/components/schemas/Task
type Task struct {
	SessionId  string         `json:"sessionId"`
	ModeName   string         `json:"modeName"`
	DocumentId string         `json:"documentId"`
	UserInput  string         `json:"userInput"`
	Selection  OptSelection   `json:"selection"`
	Options    OptTurnOptions `json:"options"`
}

// GetSessionId returns the value of SessionId.
func (s *Task) GetSessionId() string {
	return s.SessionId
}

// GetModeName returns the value of ModeName.
func (s *Task) GetModeName() string {
	return s.ModeName
}

// GetDocumentId returns the value of DocumentId.
func (s *Task) GetDocumentId() string {
	return s.DocumentId
}

// GetUserInput returns the value of UserInput.
func (s *Task) GetUserInput() string {
	return s.UserInput
}

// GetSelection returns the value of Selection.
func (s *Task) GetSelection() OptSelection {
	return s.Selection
}

// GetOptions returns the value of Options.
func (s *Task) GetOptions() OptTurnOptions {
	return s.Options
}

// SetSessionId sets the value of SessionId.
func (s *Task) SetSessionId(val string) {
	s.SessionId = val
}

// SetModeName sets the value of ModeName.
func (s *Task) SetModeName(val string) {
	s.ModeName = val
}

// SetDocumentId sets the value of DocumentId.
func (s *Task) SetDocumentId(val string) {
	s.DocumentId = val
}

// SetUserInput sets the value of UserInput.
func (s *Task) SetUserInput(val string) {
	s.UserInput = val
}

// SetSelection sets the value of Selection.
func (s *Task) SetSelection(val OptSelection) {
	s.Selection = val
}

// SetOptions sets the value of Options.
func (s *Task) SetOptions(val OptTurnOptions) {
	s.Options = val
}

// Ref: #/components/schemas/ToolDef
type ToolDef struct {
	Name        string             `json:"name"`
	Description OptString          `json:"description"`
	Parameters  *ToolDefParameters `json:"parameters"`
}

// GetName returns the value of Name.
func (s *ToolDef) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *ToolDef) GetDescription() OptString {
	return s.Description
}

// GetParameters returns the value of Parameters.
func (s *ToolDef) GetParameters() *ToolDefParameters {
	return s.Parameters
}

// SetName sets the value of Name.
func (s *ToolDef) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *ToolDef) SetDescription(val OptString) {
	s.Description = val
}

// SetParameters sets the value of Parameters.
func (s *ToolDef) SetParameters(val *ToolDefParameters) {
	s.Parameters = val
}

type ToolDefParameters struct{}

// Ref: #/components/schemas/TurnOptions
type TurnOptions struct {
	Temperature OptFloat64 `json:"temperature"`
	Model       OptString  `json:"model"`
}

// GetTemperature returns the value of Temperature.
func (s *TurnOptions) GetTemperature() OptFloat64 {
	return s.Temperature
}

// GetModel returns the value of Model.
func (s *TurnOptions) GetModel() OptString {
	return s.Model
}

// SetTemperature sets the value of Temperature.
func (s *TurnOptions) SetTemperature(val OptFloat64) {
	s.Temperature = val
}

// SetModel sets the value of Model.
func (s *TurnOptions) SetModel(val OptString) {
	s.Model = val
}

// Ref: #/components/schemas/WordEdit
type WordEdit struct {
	BlockId    string   `json:"blockId"`
	Insertions []string `json:"insertions"`
	Deletions  []string `json:"deletions"`
}

// GetBlockId returns the value of BlockId.
func (s *WordEdit) GetBlockId() string {
	return s.BlockId
}

// GetInsertions returns the value of Insertions.
func (s *WordEdit) GetInsertions() []string {
	return s.Insertions
}

// GetDeletions returns the value of Deletions.
func (s *WordEdit) GetDeletions() []string {
	return s.Deletions
}

// SetBlockId sets the value of BlockId.
func (s *WordEdit) SetBlockId(val string) {
	s.BlockId = val
}

// SetInsertions sets the value of Insertions.
func (s *WordEdit) SetInsertions(val []string) {
	s.Insertions = val
}

// SetDeletions sets the value of Deletions.
func (s *WordEdit) SetDeletions(val []string) {
	s.Deletions = val
}
