// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"context"
	"net/http"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}
var _ RawHandler = UnimplementedHandler{}

// ApplyEdit implements applyEdit operation.
//
// POST /documents/{id}/edits
func (UnimplementedHandler) ApplyEdit(ctx context.Context, req *BlockEdit, params ApplyEditParams) (r *Revision, _ error) {
	return r, ht.ErrNotImplemented
}

// CommitDocument implements commitDocument operation.
//
// Accepts the staged candidates (newest-first, deterministic), re-validates each candidate's base
// content hash, formats, makes one git commit with an auto-derived message
// (`mode · blockID · diff`), and mirrors the canonical markdown back to the opened file (ADR-0047
// §1/§5/§8). An empty accept creates no commit. If the file on disk changed since the engine last
// read it, the write-through is refused with `file-changed-externally` unless `overwrite` is true —
// never a silent clobber.
//
// POST /documents/{id}/commits
func (UnimplementedHandler) CommitDocument(ctx context.Context, req OptCommitRequest, params CommitDocumentParams) (r CommitDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSession implements createSession operation.
//
// POST /sessions
func (UnimplementedHandler) CreateSession(ctx context.Context, req *CreateSessionRequest) (r *Session, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorkspace implements createWorkspace operation.
//
// Canonicalizes the root (EvalSymlinks + case-fold): an alias or an already-open nested directory
// resumes the most specific existing workspace; otherwise a workspace is created and seeded with the
// root as its first corpus root and `**/*.md` as the default include.
//
// POST /workspaces
func (UnimplementedHandler) CreateWorkspace(ctx context.Context, req *CreateWorkspaceRequest) (r *Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// EvictCorpusDocument implements evictCorpusDocument operation.
//
// Removes the file's chunks from both the vector and full-text indexes and records an eviction
// tombstone (status `evicted` until re-indexed). No file on disk is touched. Deleting twice succeeds.
//
// DELETE /corpus/documents/{id}
func (UnimplementedHandler) EvictCorpusDocument(ctx context.Context, params EvictCorpusDocumentParams) (r EvictCorpusDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBlocks implements getBlocks operation.
//
// GET /documents/{id}/blocks
func (UnimplementedHandler) GetBlocks(ctx context.Context, params GetBlocksParams) (r []Block, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCandidates implements getCandidates operation.
//
// GET /documents/{id}/blocks/{bid}/candidates
func (UnimplementedHandler) GetCandidates(ctx context.Context, params GetCandidatesParams) (r []Candidate, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCorpus implements getCorpus operation.
//
// Read a workspace's corpus scope, per-document status, and job progress (ADR-0049 §4).
//
// GET /corpus
func (UnimplementedHandler) GetCorpus(ctx context.Context, params GetCorpusParams) (r *CorpusState, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDiff implements getDiff operation.
//
// GET /documents/{id}/diff
func (UnimplementedHandler) GetDiff(ctx context.Context, params GetDiffParams) (r []WordEdit, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFleet implements getFleet operation.
//
// The observability surface the model selectors consume. Answers 200 even when the control daemon is
// unreachable: `control` drops to "unreachable" and `models` carries the last-known projection with
// every liveState forced to "unknown" (ADR-0040 §3).
//
// GET /fleet
func (UnimplementedHandler) GetFleet(ctx context.Context) (r *FleetState, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Liveness check.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHistory implements getHistory operation.
//
// GET /documents/{id}/history
func (UnimplementedHandler) GetHistory(ctx context.Context, params GetHistoryParams) (r []Revision, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModelStatus implements getModelStatus operation.
//
// GET /models/{name}/status
func (UnimplementedHandler) GetModelStatus(ctx context.Context, params GetModelStatusParams) (r *LiveStateResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSessionMessages implements getSessionMessages operation.
//
// GET /sessions/{id}/messages
func (UnimplementedHandler) GetSessionMessages(ctx context.Context, params GetSessionMessagesParams) (r []Message, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSessionMeter implements getSessionMeter operation.
//
// Aggregates the workspace shard's meter_events for a session by component (system, tools, rag,
// history, mentions, user, thinking, completion) and returns the cumulative total. The session id is
// resolved to its workspace shard through the registry's session routing index; an unknown session is
// a typed 404.
//
// GET /sessions/{id}/meter
func (UnimplementedHandler) GetSessionMeter(ctx context.Context, params GetSessionMeterParams) (r GetSessionMeterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTurnContext implements getTurnContext operation.
//
// Returns the context snapshot the engine persisted for a turn: every assembled message with its
// component and provenance, the retrieved chunks, the labeled drops, and the budget accounting. The
// snapshot is engine data; clients render it and never reconstruct it. The turn id is resolved to its
// workspace shard through the registry's turn routing index; an unknown turn is a typed 404.
//
// GET /turns/{id}/context
func (UnimplementedHandler) GetTurnContext(ctx context.Context, params GetTurnContextParams) (r GetTurnContextRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspace implements getWorkspace operation.
//
// Read one workspace record.
//
// GET /workspaces/{id}
func (UnimplementedHandler) GetWorkspace(ctx context.Context, params GetWorkspaceParams) (r *Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// IndexCorpus implements indexCorpus operation.
//
// Bulk (re)index the current scope; async, idempotent per unchanged content (ADR-0049 §4).
//
// POST /corpus/index
func (UnimplementedHandler) IndexCorpus(ctx context.Context, req *CorpusIndexRequest) (r *CorpusJob, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDirectory implements listDirectory operation.
//
// Bounded by ALLOWED_ROOTS (ADR-0049 §6): a path outside the allowlist is refused with the typed
// `path-outside-allowed-roots` error, never silently.
//
// GET /directories
func (UnimplementedHandler) ListDirectory(ctx context.Context, params ListDirectoryParams) (r ListDirectoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListModels implements listModels operation.
//
// Deprecated for clients — use /fleet (ADR-0040). Retained for compatibility.
//
// GET /models
func (UnimplementedHandler) ListModels(ctx context.Context) (r []Model, _ error) {
	return r, ht.ErrNotImplemented
}

// ListModes implements listModes operation.
//
// GET /modes
func (UnimplementedHandler) ListModes(ctx context.Context) (r []Mode, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSessions implements listSessions operation.
//
// Lists sessions newest-first. At least one of `workspaceId` or `documentId` is required:
// `workspaceId` selects the workspace shard directly; `documentId` resolves the workspace that
// contains the document (fallback). Both filters may be combined.
//
// GET /sessions
func (UnimplementedHandler) ListSessions(ctx context.Context, params ListSessionsParams) (r []Session, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTools implements listTools operation.
//
// GET /tools
func (UnimplementedHandler) ListTools(ctx context.Context) (r []ToolDef, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkspaces implements listWorkspaces operation.
//
// List the workspace registry (ADR-0049 §2).
//
// GET /workspaces
func (UnimplementedHandler) ListWorkspaces(ctx context.Context) (r []Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// OpenDocument implements openDocument operation.
//
// Open/create a document by path; returns its surrogate id.
//
// POST /documents
func (UnimplementedHandler) OpenDocument(ctx context.Context, req *OpenDocumentRequest) (r *Document, _ error) {
	return r, ht.ErrNotImplemented
}

// ProvisionModel implements provisionModel operation.
//
// POST /models/{name}/provision
func (UnimplementedHandler) ProvisionModel(ctx context.Context, params ProvisionModelParams) (r *ProvisionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// PutCorpus implements putCorpus operation.
//
// Roots are canonicalized and deduped; include/exclude globs decide retrievability (default `**/*.md`,
// hidden directories excluded). The scope change reconciles the index asynchronously; no document file
// is ever created, modified, or deleted. A root outside ALLOWED_ROOTS is refused with the typed
// `path-outside-allowed-roots`.
//
// PUT /corpus
func (UnimplementedHandler) PutCorpus(ctx context.Context, req *PutCorpusRequest) (r PutCorpusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutSessionContext implements putSessionContext operation.
//
// Replaces the session's persisted context policy (pins, excludes, auto-RAG flag, retrieval query) and
// returns the session so the client reads back what was persisted. The policy carries the same shape
// as the per-turn `Task.context` override; it survives turns, reconnects, and session resume. Per-turn
// overrides are never persisted. An unknown session is the typed 404.
//
// PUT /sessions/{id}/context
func (UnimplementedHandler) PutSessionContext(ctx context.Context, req *ContextPolicy, params PutSessionContextParams) (r PutSessionContextRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResolveLocate implements resolveLocate operation.
//
// When a `/locate` turn resolves to a fuzzy match it emits a `locate` event with ranked candidates and
// waits (bounded) for the user's choice. This route resumes the turn: pick a candidate by its
// `chunkKey`, or cancel to degrade the turn to plain chat. No model call and no edit happen before the
// choice. An unknown turn id is a typed 404; a turn that is not waiting on a picker (already answered,
// timed out, or never ambiguous) is a typed 409.
//
// POST /turns/{id}/locate
func (UnimplementedHandler) ResolveLocate(ctx context.Context, req *LocateChoice, params ResolveLocateParams) (r ResolveLocateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SaveDocument implements saveDocument operation.
//
// The manual-edit wire path (ADR-0038): the client's whole block-tree snapshot. Array order =
// position; a block with no `id` is new (the engine mints a UUID, ADR-0020 §3); an `id` present in
// the current tree but absent from the request is deleted; a changed `kind`/`parentId` is
// retyped/moved. The engine reconciles, normalizes on write and formats on commit, and commits
// `autosave @ <ts>` iff anything changed (a no-op returns the current HEAD). A manual save of a block
// drops its open candidates. When `writeThrough` is true (explicit Save / Cmd+S, not the periodic
// autosave), the engine also mirrors the canonical markdown back to the opened file path (ADR-0039).
// Per ADR-0047 §4 a no-op save still re-syncs a stale disk (no new commit), and an external change
// surfaces as a `file-changed-externally` conflict — never a silent clobber.
//
// PUT /documents/{id}/tree
func (UnimplementedHandler) SaveDocument(ctx context.Context, req *SaveTreeRequest, params SaveDocumentParams) (r SaveDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartModel implements startModel operation.
//
// POST /models/{name}/start
func (UnimplementedHandler) StartModel(ctx context.Context, params StartModelParams) (r *LiveStateResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// StartTurn implements startTurn operation.
//
// Run one agent turn (SSE stream).
//
// POST /turn
func (UnimplementedHandler) StartTurn(ctx context.Context, req *Task, w http.ResponseWriter) error {
	return ht.ErrNotImplemented
}

// StopModel implements stopModel operation.
//
// POST /models/{name}/stop
func (UnimplementedHandler) StopModel(ctx context.Context, params StopModelParams) (r *LiveStateResponse, _ error) {
	return r, ht.ErrNotImplemented
}
